### ISSUE TITLE
Loot_Box Procedure

### ISSUE THREAD

**Issue by Edak0** [Code-Ninjas-Kyle/Minecraft-ModCamp#1]
procedure seems to be impossible as according to camp
![image](https://user-images.githubusercontent.com/33668469/74069845-f9b49300-49c4-11ea-8aa3-995852ad0a6f.png)

 when i attempt to attach the Get block to the main block it refuses to attach unlike the given picture given in the instructions 
(where i hold it)
![image](https://user-images.githubusercontent.com/33668469/74069810-e6092c80-49c4-11ea-86f1-1a6d9ee84769.png)
(where it snaps to)
![image](https://user-images.githubusercontent.com/33668469/74069821-eb667700-49c4-11ea-9150-234a52ad6bd1.png)
(picture i was given as reference)
![Loot Block Script](https://user-images.githubusercontent.com/33668469/74069977-4dbf7780-49c5-11ea-9507-4dfd7fb003a5.PNG)

**Comment by MatrixSenpai** [comment]
Lets get the source documents for the camp from @ctphillips and see if we can find and resolve this issue

**Comment by MatrixSenpai** [comment]
Fixed as of most recent version
